const MAPA_TERMOS = [
  { termos: ["abacate"], produto: "Abacate" },
  { termos: ["abacaxi", "perola"], produto: "Abacaxi Perola" },
  { termos: ["abobora", "pescoco"], produto: "Abobora Pescoco" },
  { termos: ["alecrim"], produto: "Alecrim" },
  { termos: ["alho", "poro"], produto: "Alho Poro" },
  { termos: ["ameixa", "500"], produto: "Ameixa 500g" },
  { termos: ["batata", "salsa"], produto: "Batata Salsa" },
  { termos: ["batata", "doce", "branca"], produto: "Batata Doce Branca" },
  { termos: ["batata", "doce", "roxa"], produto: "Batata Doce Roxa" },
  { termos: ["berinjela"], produto: "Berinjela" },
  { termos: ["beterraba"], produto: "Beterraba" },
  { termos: ["blueberry", "125"], produto: "Blueberry 125g" },
  { termos: ["caqui", "rama", "forte"], produto: "Caqui Rama Forte" },
  { termos: ["carambola", "400"], produto: "Carambola 400g" },
  { termos: ["cebola", "argentina"], produto: "Cebola Albina" },
  { termos: ["cebola", "branca"], produto: "Cebola Albina" },
  { termos: ["cebola", "conserva"], produto: "Cebola Conserva" },
  { termos: ["cenoura"], produto: "Cenoura" },
  { termos: ["chuchu"], produto: "Chuchu" },
  { termos: ["coco", "seco"], produto: "Coco Seco" },
  { termos: ["coentro"], produto: "Coentro" },
  { termos: ["figo"], produto: "Figo Roxo" },
  { termos: ["goiaba", "vermelha"], produto: "Goiaba Vermelha" },
  { termos: ["hortela"], produto: "Hortela" },
  { termos: ["jatoba"], produto: "Jatoba" },
  { termos: ["kiwi", "cumbuca"], produto: "Kiwi Cumbuca" },
  { termos: ["kiwi"], produto: "Kiwi" },
  { termos: ["louro"], produto: "Louro" },
  { termos: ["mamao", "formosa"], produto: "Mamao Formosa" },
  { termos: ["mamaozinho", "papaia"], produto: "Mamão Papaya" },
  { termos: ["mamão", "papaya"], produto: "Mamão Papaya" },
  { termos: ["manga", "palmer"], produto: "Manga Palmer" },
  { termos: ["manjericao"], produto: "Manjericao" },
  { termos: ["manjerona"], produto: "Manjerona" },
  { termos: ["maxixe", "300"], produto: "Maxixe 300g" },
  { termos: ["melao", "cantaloupe"], produto: "Melão Cantaloupe" },
  { termos: ["melao", "charanteais"], produto: "Melão Charanteais" },
  { termos: ["melao", "dino"], produto: "Melão Dino" },
  { termos: ["melao", "espanhol"], produto: "Melão Amarelo" },
  { termos: ["melao", "amarelo"], produto: "Melão Amarelo" },
  { termos: ["melao", "galia"], produto: "Melão Galia" },
  { termos: ["melao", "orange"], produto: "Melão Orange" },
  { termos: ["melao", "rei"], produto: "Melão Rei" },
  { termos: ["melao", "redinha"], produto: "Melão Rei" },
  { termos: ["melao", "sapo"], produto: "Melão Pele de Sapo" },
  { termos: ["milho", "verde"], produto: "Milho Verde" },
  { termos: ["mirtilo"], produto: "Blueberry 125g" },
  { termos: ["nabo"], produto: "Nabo" },
  { termos: ["pepino", "japones"], produto: "Pepino Japones" },
  { termos: ["pera", "willians"], produto: "Pera Willians" },
  { termos: ["physalis"], produto: "Physalis 100g" },
  { termos: ["pimenta", "biquinho"], produto: "Pimenta Biquinho" },
  { termos: ["pimenta", "cambuci"], produto: "Pimenta Cambuci" },
  { termos: ["pimenta", "jalapeno"], produto: "Pimenta Jalapeno" },
  { termos: ["salsao", "aipo"], produto: "Salsao" },
  { termos: ["salvia"], produto: "Salvia" },
  { termos: ["tomate", "grape"], produto: "Tomate Grap" },
  { termos: ["sweet", "grape"], produto: "Tomate Grap" },
  { termos: ["tomilho"], produto: "Tomilho" },
  { termos: ["uva", "thompson", "500"], produto: "Uva Thompson 500g" }
];
